# https://vkhost.github.io/ 
# Kate Mobile, далее скопировать токен сюда из адресной строки
# Токен бесрочный обновлять не нужно! Если нужно будет отозвать, задйите в настройки! 
# Вместо токена можно по телефону и паролю
token: "vk1.a.XXXXXX"

# 
# Необязательно можно указать при инсталяции
#
phone: +79XXXX
ppasword: XXXXX

# Идентификатор группы (в ссылке на группу https://vk.com/clubXXXXX)
group_id: 222485128

# Сообщение при отправке (если не нужно, оставить пустым)
message: ""

# Время отправки
date: "19:16"

# Промежуток между проверками времени (в секундах)
delay: 120
